import { auth, db, authPersistenceReady } from "../login/firebase-config.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { ref, push, set, onValue, remove, update } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";

let receipts=[];let currentUser=null;let editingId=null;let unsubscribeReceipts=null;
const list=document.querySelector("#receiptList"),search=document.querySelector("#searchInput"),filter=document.querySelector("#categoryFilter"),modal=document.querySelector("#scanModal"),editModal=document.querySelector("#editModal"),syncBadge=document.querySelector(".live-badge");
function won(n){return new Intl.NumberFormat("ko-KR").format(Number(n)||0)+"원"}
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function localTime(d=new Date()){return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`}
function receiptDateTime(r){return new Date(`${r.date||"1970-01-01"}T${r.time||"00:00"}:00`)}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function setSyncStatus(text,online=true){if(!syncBadge)return;syncBadge.textContent=text;syncBadge.style.color=online?"#19905a":"#c24141";syncBadge.style.background=online?"#f2fdf7":"#fff5f5";syncBadge.style.borderColor=online?"#d9f4e6":"#f2d7d7"}
function render(){const q=search.value.trim().toLowerCase(),category=filter.value,filtered=receipts.filter(r=>(category==="all"||r.category===category)&&(`${r.store||""} ${r.item||""}`.toLowerCase().includes(q)));list.innerHTML=filtered.length?filtered.map(r=>`<article class="receipt-row"><div class="receipt-icon">₩</div><div class="receipt-info"><strong>${escapeHtml(r.store)}</strong><span>${escapeHtml(r.item)} · ${escapeHtml(r.category)}</span></div><div class="receipt-date">${escapeHtml(r.date)} ${escapeHtml(r.time||"")}</div><strong class="receipt-amount">${won(r.amount)}</strong><div class="receipt-actions"><button class="edit-receipt" data-id="${escapeHtml(r.id)}" type="button">수정</button><button class="delete-receipt" data-id="${escapeHtml(r.id)}" type="button">삭제</button></div></article>`).join(""):<div class="empty">아직 영수증이 없습니다.<br><span>영수증 추가 버튼으로 첫 영수증을 저장해보세요.</span></div>`;const month=localDate().slice(0,7),monthReceipts=receipts.filter(r=>String(r.date||"").startsWith(month));document.querySelector("#monthTotal").textContent=won(monthReceipts.reduce((s,r)=>s+Number(r.amount||0),0));document.querySelector("#receiptCount").textContent=`${receipts.length}장`;document.querySelector("#monthCount").textContent=`${monthReceipts.length}장`}
function listenReceipts(uid){if(unsubscribeReceipts)unsubscribeReceipts();const receiptsRef=ref(db,`users/${uid}/receipts`);setSyncStatus("Firebase 연결 중...",false);unsubscribeReceipts=onValue(receiptsRef,snapshot=>{const data=snapshot.val()||{};receipts=Object.entries(data).map(([id,receipt])=>({id,...receipt})).sort((a,b)=>receiptDateTime(b)-receiptDateTime(a));render();setSyncStatus("Firebase 동기화됨",true)},error=>{console.error("Firebase 영수증 동기화 실패:",error);setSyncStatus("Firebase 연결 실패",false);list.innerHTML=`<div class="empty">Firebase에서 영수증을 불러오지 못했습니다.<br><span>${escapeHtml(error.message)}</span></div>`})}
async function saveReceiptToFirebase(receipt){if(!currentUser)throw new Error("로그인 상태가 아닙니다.");await set(push(ref(db,`users/${currentUser.uid}/receipts`)),receipt)}
async function deleteReceipt(id){if(!currentUser||!id)return;if(!confirm("이 영수증을 삭제할까요?"))return;try{await remove(ref(db,`users/${currentUser.uid}/receipts/${id}`))}catch(error){alert(`영수증 삭제에 실패했습니다.\n${error.message||"Firebase 설정을 확인해주세요."}`)}}
function openEdit(id){const receipt=receipts.find(r=>r.id===id);if(!receipt)return;editingId=id;document.querySelector("#editStoreInput").value=receipt.store||"";document.querySelector("#editAmountInput").value=Number(receipt.amount)||"";document.querySelector("#editCategoryInput").value=receipt.category||"기타";document.querySelector("#editItemInput").value=receipt.item||"";document.querySelector("#editDateInput").value=receipt.date||localDate();document.querySelector("#editTimeInput").value=receipt.time||"00:00";editModal.classList.remove("hidden")}
function closeEdit(){editingId=null;editModal.classList.add("hidden")}
async function updateReceipt(){if(!currentUser||!editingId)return;const store=document.querySelector("#editStoreInput").value.trim(),amount=Number(document.querySelector("#editAmountInput").value),category=document.querySelector("#editCategoryInput").value,item=document.querySelector("#editItemInput").value.trim()||"상품 정보 없음",date=document.querySelector("#editDateInput").value,time=document.querySelector("#editTimeInput").value||"00:00";if(!store||!amount||!date)return alert("가게명, 금액, 날짜를 입력해주세요.");try{await update(ref(db,`users/${currentUser.uid}/receipts/${editingId}`),{store,amount,category,item,date,time});closeEdit()}catch(error){alert(`영수증 수정에 실패했습니다.\n${error.message||"Firebase 설정을 확인해주세요."}`)}}
onAuthStateChanged(auth,user=>{if(!user){window.location.replace("../login/");return}currentUser=user;const nickname=user.displayName?.trim()||user.email?.split("@")[0]||"사용자";document.querySelector("#welcomeMessage").textContent=`${nickname}님 안녕하세요`;document.querySelector("#userEmail").textContent=user.email||"";const now=new Date();document.querySelector("#dateInput").value=localDate(now);document.querySelector("#timeInput").value=localTime(now);listenReceipts(user.uid)});
onValue(ref(db,".info/connected"),snap=>{if(snap.val()===true)setSyncStatus("Firebase 연결됨",true);else setSyncStatus("Firebase 오프라인",false)});
document.querySelector("#logoutBtn").addEventListener("click",async()=>{try{await authPersistenceReady;await signOut(auth)}finally{window.location.replace("../login/")}});document.querySelector("#scanBtn").addEventListener("click",()=>{const now=new Date();document.querySelector("#dateInput").value=localDate(now);document.querySelector("#timeInput").value=localTime(now);modal.classList.remove("hidden")});document.querySelector("#closeModal").addEventListener("click",()=>modal.classList.add("hidden"));document.querySelector("#closeEditModal").addEventListener("click",closeEdit);document.querySelector("#cancelEdit").addEventListener("click",closeEdit);document.querySelector("#updateReceipt").addEventListener("click",updateReceipt);search.addEventListener("input",render);filter.addEventListener("change",render);list.addEventListener("click",event=>{const editButton=event.target.closest(".edit-receipt"),deleteButton=event.target.closest(".delete-receipt");if(editButton)openEdit(editButton.dataset.id);if(deleteButton)deleteReceipt(deleteButton.dataset.id)});
document.querySelector("#saveReceipt").addEventListener("click",async()=>{if(!currentUser)return alert("로그인 상태를 확인해주세요.");const store=document.querySelector("#storeInput").value.trim(),amount=Number(document.querySelector("#amountInput").value),category=document.querySelector("#categoryInput").value,item=document.querySelector("#itemInput").value.trim()||"상품 정보 없음",date=document.querySelector("#dateInput").value||localDate(),time=document.querySelector("#timeInput").value||localTime();if(!store||!amount)return alert("가게명과 금액을 입력해주세요.");const receipt={store,item,amount,category,date,time};try{setSyncStatus("Firebase 저장 중...",false);await saveReceiptToFirebase(receipt);["storeInput","amountInput","itemInput"].forEach(id=>document.querySelector(`#${id}`).value="");modal.classList.add("hidden")}catch(error){setSyncStatus("Firebase 저장 실패",false);alert(`영수증 저장에 실패했습니다.\n${error.message||"Firebase 설정을 확인해주세요."}`)}});
