import { auth, authPersistenceReady } from "../login/firebase-config.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getDatabase, ref, onValue } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";

const db=getDatabase(), period=document.body.dataset.period; let receipts=[];
const won=n=>new Intl.NumberFormat("ko-KR").format(Math.round(n||0))+"원";
const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const dateOf=r=>new Date(`${r.date||"1970-01-01"}T${r.time||"00:00"}:00`);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function startOfWeek(d){const x=new Date(d);const day=x.getDay();x.setDate(x.getDate()-(day===0?6:day-1));x.setHours(0,0,0,0);return x}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function fmt(d,opt={}){return new Intl.DateTimeFormat("ko-KR",opt).format(d)}
function sum(rs){return rs.reduce((a,r)=>a+Number(r.amount||0),0)}
function sameDate(r,d){return r.date===key(d)}
function inRange(r,a,b){const d=dateOf(r);return d>=a&&d<b}
function selectedDay(){const p=new URLSearchParams(location.search).get("date");if(period!=="day")return new Date();if(/^\d{4}-\d{2}-\d{2}$/.test(p||"")){const [y,m,d]=p.split("-").map(Number);const x=new Date(y,m-1,d);if(x.getFullYear()===y&&x.getMonth()===m-1&&x.getDate()===d)return x}const x=new Date();x.setHours(0,0,0,0);return x}
function currentData(){const now=new Date();now.setHours(0,0,0,0);if(period==="day"){const s=selectedDay();s.setHours(0,0,0,0);return{start:s,end:addDays(s,1),label:fmt(s,{year:"numeric",month:"long",day:"numeric",weekday:"long"})}}if(period==="week"){const s=startOfWeek(now);return{start:s,end:addDays(s,7),label:`${fmt(s,{month:"short",day:"numeric"})} ~ ${fmt(addDays(s,6),{month:"short",day:"numeric"})}`}}if(period==="month"){const s=new Date(now.getFullYear(),now.getMonth(),1);return{start:s,end:new Date(now.getFullYear(),now.getMonth()+1,1),label:fmt(s,{year:"numeric",month:"long"})}}const s=new Date(now.getFullYear(),0,1);return{start:s,end:new Date(now.getFullYear()+1,0,1),label:fmt(s,{year:"numeric"})}}
const labels={day:"일별",week:"주별",month:"달별",year:"연별"};
const descriptions={day:"하루의 지출을 실제 결제 시간 기준으로 확인하세요.",week:"한 주를 달력으로 보면서 어느 날 지출했는지 확인하세요.",month:"이번 달의 소비 흐름을 달력과 함께 확인하세요.",year:"올해 12개월의 지출 흐름을 한눈에 확인하세요."};
function render(){const{start,end,label}=currentData();const current=receipts.filter(r=>inRange(r,start,end));document.querySelector("#periodTotal").textContent=won(sum(current));document.querySelector("#periodCount").textContent=`${current.length}장`;document.querySelector("#avgAmount").textContent=won(current.length?sum(current)/current.length:0);document.querySelector("#welcome").textContent=`${window.receiptUserName||"사용자"}님의 ${labels[period]} 지출`;const desc=document.querySelector("#description");if(desc)desc.textContent=descriptions[period];renderSpecial(start);renderCategories(current);renderReceipts(current);if(period==="day")updateDayControls(start)}
function renderSpecial(start){if(period==="day")renderDay(start);if(period==="week")renderWeek(start);if(period==="month")renderMonth(start);if(period==="year")renderYear(start)}
function renderDay(start){const vals=Array.from({length:24},(_,h)=>sum(receipts.filter(r=>sameDate(r,start)&&dateOf(r).getHours()===h)));const max=Math.max(...vals,1);document.querySelector("#specialView").innerHTML=`<div class="day-hours">${vals.map((v,h)=>`<div class="hour-row"><span class="hour-label">${String(h).padStart(2,"0")}시</span><div class="hour-track"><i style="width:${v?Math.max(v/max*100,4):0}%"></i></div><strong>${v?won(v):"-"}</strong></div>`).join("")}</div>`}
function renderWeek(start){const days=Array.from({length:7},(_,i)=>addDays(start,i));document.querySelector("#specialView").innerHTML=`<div class="week-calendar">${days.map(d=>{const rs=receipts.filter(r=>sameDate(r,d)),total=sum(rs);return `<div class="week-day ${key(d)===key(new Date())?"today":""}"><div class="week-day-head"><span>${["월","화","수","목","금","토","일"][d.getDay()===0?6:d.getDay()-1]}</span><b>${d.getDate()}</b></div><div class="week-day-total">${total?won(total):"-"}</div><div class="week-dots">${rs.slice(0,3).map(()=>"<i></i>").join("")}</div></div>`}).join("")}</div>`}
function renderMonth(start){const firstDay=new Date(start.getFullYear(),start.getMonth(),1),days=new Date(start.getFullYear(),start.getMonth()+1,0).getDate(),offset=(firstDay.getDay()+6)%7;let cells="";for(let i=0;i<offset;i++)cells+='<div class="month-cell empty-cell"></div>';for(let n=1;n<=days;n++){const d=new Date(start.getFullYear(),start.getMonth(),n),total=sum(receipts.filter(r=>sameDate(r,d)));cells+=`<div class="month-cell ${key(d)===key(new Date())?"today":""}"><span>${n}</span>${total?`<strong>${won(total).replace("원","")}</strong>`:""}</div>`}document.querySelector("#specialView").innerHTML=`<div class="calendar-weekdays">${["월","화","수","목","금","토","일"].map(x=>`<span>${x}</span>`).join("")}</div><div class="month-calendar">${cells}</div>`}
function renderYear(start){const months=Array.from({length:12},(_,i)=>new Date(start.getFullYear(),i,1)),vals=months.map(d=>sum(receipts.filter(r=>r.date?.startsWith(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`)))),max=Math.max(...vals,1);document.querySelector("#specialView").innerHTML=`<div class="year-grid">${months.map((d,i)=>`<div class="year-month"><span>${i+1}월</span><strong>${won(vals[i])}</strong><div class="year-track"><i style="height:${Math.max(vals[i]/max*100,vals[i]?6:2)}%"></i></div></div>`).join("")}</div>`}
function renderCategories(rs){const cats=["식비","카페","쇼핑","교통","의료","기타"],vals=cats.map(c=>({c,v:sum(rs.filter(r=>r.category===c))})),max=Math.max(...vals.map(x=>x.v),1);document.querySelector("#categories").innerHTML=vals.map(x=>`<div class="cat-row"><span class="cat-name">${x.c}</span><div class="track"><div class="fill" style="width:${x.v/max*100}%"></div></div><span class="cat-amount">${won(x.v)}</span></div>`).join("")}
function renderReceipts(rs){const sorted=[...rs].sort((a,b)=>dateOf(b)-dateOf(a));document.querySelector("#receipts").innerHTML=sorted.length?sorted.slice(0,50).map(r=>`<div class="receipt"><div class="icon">▣</div><div><strong>${esc(r.store)}</strong><span>${esc(r.item)} · ${esc(r.category)}</span></div><span class="date">${esc(r.date)} ${esc(r.time||"")}</span><strong class="amount">${won(r.amount)}</strong></div>`).join(""):`<div class="empty"><b>아직 영수증이 없어요</b>영수증을 추가하면 이곳에 자동으로 모아집니다.</div>`}
function updateDayControls(date){const prev=document.querySelector("#prevDay"),next=document.querySelector("#nextDay"),today=document.querySelector("#todayDay");if(!prev)return;const todayKey=key(new Date()),selectedKey=key(date);prev.onclick=()=>{location.href=`./?date=${key(addDays(date,-1))}`};today.onclick=()=>{location.href="./"};next.disabled=selectedKey>=todayKey;next.onclick=()=>{if(selectedKey<todayKey)location.href=`./?date=${key(addDays(date,1))}`};next.classList.toggle("disabled",next.disabled)}
onAuthStateChanged(auth,user=>{if(!user){location.replace("../login/");return}window.receiptUserName=user.displayName?.trim()||user.email?.split("@")[0]||"사용자";onValue(ref(db,`users/${user.uid}/receipts`),snap=>{const data=snap.val()||{};receipts=Object.entries(data).map(([id,r])=>({id,...r}));render()},err=>{const s=document.querySelector("#status");if(s)s.textContent=err.message})});
document.querySelector("#logout").addEventListener("click",async()=>{await authPersistenceReady;await signOut(auth);location.replace("../login/")});
